apiVersion: apps/v1
kind: Deployment
metadata:
  name: wealthmanagement
  labels:
    app: wealthmanagement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wealthmanagement
  template:
    metadata:
      labels:
        app: wealthmanagement
    spec:
      containers:
      - name: wealthmanagement
        image: apmpacr.azurecr.io/wealthmanagement:v4
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_APPLICATION_NAME
          value: wealthmanagement
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: cosmosdb-secret
              key: MONGODB_URI
        - name: SPRING_DATA_MONGODB_DATABASE
          value: "apmp-cosmos"
        - name: SPRING_PROFILES_ACTIVE
          value: "test"
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-oauth-secret
              key: client-id
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-oauth-secret
              key: client-secret
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE
          value: "profile,email"
        - name: SPRING_AUTOCONFIGURE_EXCLUDE
          value: ""