apiVersion: apps/v1
kind: Deployment
metadata:
  name: wealthmanagement
  labels:
    app: wealthmanagement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wealthmanagement
  template:
    metadata:
      labels:
        app: wealthmanagement
    spec:
      containers:
      - name: wealthmanagement
        image: apmpacr.azurecr.io/wealthmanagement:v2
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_APPLICATION_NAME
          value: wealthmanagement
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: cosmosdb-secret
              key: MONGODB_URI
        - name: SPRING_DATA_MONGODB_DATABASE
          value: "wealthmanagement-db"