apiVersion: v1
kind: Service
metadata:
  name: wealthmanagement-service
spec:
  selector:
    app: wealthmanagement
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
