spring.application.name=wealthmanagement

# https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db
# Specify the DNS URI of your Azure Cosmos DB.
# spring.cloud.azure.cosmos.endpoint=https://contosoaccounttest.documents.azure.com:443/
# spring.cloud.azure.cosmos.key=your-cosmosdb-account-key

# # Specify the name of your database.
# spring.cloud.azure.cosmos.database=contosoaccounttest
# spring.cloud.azure.cosmos.populate-query-metrics=true
