FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci --force

COPY . .
RUN npm run build --configuration=production

FROM nginx:alpine
COPY --from=build /app/dist/WealthManagementFrontEnd/browser /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx-default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]